plugins {
	id 'com.android.application'
}

android {
	namespace 'hopebridgenew.mobile'
	compileSdk 36

	defaultConfig {
		applicationId 'kr.or.gapdr.hopebridge.maintenance2026'
		minSdk 24
		targetSdk 36
		versionCode 1
		versionName '1.0.0'
	}

	buildTypes {
		debug {
			applicationIdSuffix ''
		}
		release {
			minifyEnabled false
		}
	}

	compileOptions {
		sourceCompatibility JavaVersion.VERSION_17
		targetCompatibility JavaVersion.VERSION_17
	}
}
